# Disable RØDE USB microphone's output sinks.
# Does not block microphone inputs.
monitor.alsa.rules = [
  {
    matches = [
      # Tilde prefix makes it a regex rule.
      { node.name = "~alsa_output.usb-R__DE_Microphones.*" }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
